# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicsher',
            new_name='Public',
        ),
    ]
