# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-24 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180824_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Public',
            new_name='Publicsher',
        ),
    ]
