# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicsher',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
