# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20180827_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicsher',
        ),
    ]
