# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_book_publicsher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicsher',
            new_name='Publisher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
