# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='title',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
