# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_publisher_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_id',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
