# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20180827_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='雁塔西路', max_length=128),
        ),
    ]
